hercules-team/augeas

- lenses/exports.aug
- lenses/tests/test_exports.aug
Hi,
This patch add support for character class lists within [square brackets].
Thanks!
> exports: add bracket support to the supported machine name formats.

- lenses/httpd.aug
As per the request in launchpad: https://bugs.launchpad.net/ubuntu/+source/augeas/+bug/1425183
> Added support for conf-available apache config file location

- lenses/httpd.aug
- lenses/tests/test_httpd.aug
The latest httpd.aug seems to have some issues handling comments. For example:
```
<IfDefine Foo>
##
##
</IfDefine>
```
results in
```
/augeas/files/usr/apache/conf/ssl.conf/error = "parse_failed"
/augeas/files/usr/apache/conf/ssl.conf/error/pos = "18"
/augeas/files/usr/apache/conf/ssl.conf/error/line = "3"
/augeas/files/usr/apache/conf/ssl.conf/error/char = "0"
/augeas/files/usr/apache/conf/ssl.conf/error/lens = "/path/to/augeas-1.3.0/share/augeas/lenses/dist/httpd.aug:97.10-.44:"
/augeas/files/usr/apache/conf/ssl.conf/error/message = "Syntax error"
```
However (note the single deleted '#' char),
```
<IfDefine Foo>
#
##
</IfDefine>
```
parses successfully. This problem doesn't occur in the 1.2.0 release.
> Httpd: error parsing comments

- lenses/mcollective.aug
In the latest release of Puppet, the mcollective paths have been updated
to reflect the documentation at
https://github.com/puppetlabs/puppet-specifications/blob/master/file_paths.md
This commit adds server.cfg and client.cfg in
/etc/puppetlabs/mcollective to the mcollective filter.
> Add /etc/puppetlabs/mcollective to mcollective lens

- lenses/chrony.aug
- lenses/tests/test_chrony.aug
In chrony-2.0 was added a new directive to specify a pool of NTP servers
and there are also several new options that can be used with the
server/peer/pool directives.
> Chrony: update for chrony 2.0

- NEWS
- lenses/shellvars.aug
- lenses/tests/test_shellvars.aug
This PR intends to parse more shellvar files by trying to parse most commands.
E.g.:
```shell
$ cat /usr/local/bin/sh2js 
#!/bin/sh
cd /opt/shjs-0.6/
./sh2js.pl $@
$ augtool -I lenses/ --noautoload -t "Shellvars.lns incl /usr/local/bin/sh2js" print /files
/files
/files/usr
/files/usr/local
/files/usr/local/bin
/files/usr/local/bin/sh2js
/files/usr/local/bin/sh2js/#comment = "!/bin/sh"
/files/usr/local/bin/sh2js/@command[1] = "cd"
/files/usr/local/bin/sh2js/@command[1]/@arg = "/opt/shjs-0.6/"
/files/usr/local/bin/sh2js/@command[2] = "./sh2js.pl"
/files/usr/local/bin/sh2js/@command[2]/@arg = "$@"
```
> Shellvars: Allow (almost) any command

- lenses/rsyslog.aug
- lenses/syslog.aug
- lenses/tests/test_rsyslog.aug
- lenses/tests/test_syslog.aug
- Treat whitespace after commas as optional.
- Recognize '~' as a valid syslog action (discard).
> Rsyslog: Improve property filter parsing.

- NEWS
- lenses/shellvars.aug
- lenses/tests/test_shellvars.aug
The shellvars lens fails to handle code like the following:
```
[ ! -z $DEBUG ] && ENABLE_DEBUG="1"
```
or
```
grep -q "Debian" /etc/issue && DEBIAN=1
```
or other variations of this kind of expressions.
> shellvars lens can't handle "expression1 && expression2" or "expression1 || expression2"

- lenses/reprepro_uploaders.aug
- lenses/tests/test_reprepro_uploaders.aug
reprepro's `uploaders` file can contain `group` definitions, see [doc](https://mirrorer.alioth.debian.org/reprepro.1.html#UPLOADERS%20FILES). Unless I'm wrong, those items are not parsed by the lens.
```
allow condition by group groupname
which allows every member of group groupname. Groups can be manipulated by
group groupname add key-id
to add a key-id (see above for details) to this group, or
group groupname contains groupname
to add a whole group to a group.
To avoid warnings in incomplete config files there is also
group groupname empty
to declare a group has no members (avoids warnings that it is used without those) and
group groupname unused
to declare that a group is not yet used (avoid warnings that it is not used).
```
> reprepro_uploader lens doesn't support groups

- lenses/multipath.aug
- lenses/tests/test_multipath.aug
Improved previous pull request. Now all keywords available in centos6 should be present. Adapted multipath test, to test a new keywords also.
> multipath.conf lense: added bunch of missing keywords

- lenses/dhclient.aug
- lenses/tests/test_dhclient.aug
When `dhclient.conf` contains a line like:
```
send host-name = gethostname();
```
*any* change to the file fails to save, since it expects a mandatory value for the node. This PR fixes this by separating the case with a node value from the cases without.
> Dhclient: avoid put ambiguity for node without value

- lenses/aptsources.aug
- lenses/tests/test_aptsource.aug
Sources.list files may contain options in the format "[arch=amd64,armhf]" immediately after type field.  This is not understood properly understood by the aptsources lens leading to incorrect parsing.  For example, with the following repository lines in sources.list:
```
deb [arch=amd64] tor+http://ftp.us.debian.org/debian sid main contrib
deb [ arch=amd64 trusted=true ] http://ftp.us.debian.org/debian sid main contrib
```
Augeas parses parses as follows:
```
augtool> ls /files/etc/apt/sources.list/1
type = deb
uri = [arch=amd64]
distribution = tor+http://ftp.us.debian.org/debian
component[1] = sid
component[2] = main
component[3] = contrib
component[4] = non-free
augtool> ls /files/etc/apt/sources.list/2
type = deb
uri = [
distribution = arch=amd64
component[1] = trusted=true …
```
> Aptsources lens can't handle [ options ] in /etc/apt/sources.list

- lenses/aptsources.aug
- lenses/tests/test_aptsource.aug
CDROM URLs in /etc/apt/sources.list may contain spaces in them.  This is not properly handled by `aptsources` lens properly.  For example, the following is a valid sources.list repository entry.
```
deb cdrom:[Debian GNU/Linux 7.5.0 _Wheezy_ - Official amd64 CD Binary-1 20140426-13:37]/ wheezy main
```
With this entry, aptsources lens parses as follows:
```
augtool> ls /files/etc/apt/sources.list/1
type = deb
uri = cdrom:[Debian
distribution = GNU/Linux
component[1] = 7.5.0
component[2] = _Wheezy_
component[3] = -
component[4] = Official
component[5] = amd64
component[6] = CD
component[7] = Binary-1
component[8] = 20140426-13:37]/
component[9] = wheezy
component[10] = main
augtool> 
```
Aptsources lens should be fixed to allow spaces in URL when enclosed in "[" and "]".
> Aptsources lens can't handle cdrom:// URLs properly

- .gitignore
- src/internal.h
- src/pathx.c
- src/try
- tests/Makefile.am
- tests/test-perf.c
Path expressions of the form `service[75]` were very slow when there were a large number of `service` nodes. These patches try to speed that up.
Tons of thanks to @domcleal for figuring out why this was slow, writing a test that demonstrates the problem and providing lots of detail on what exactly was going on.
> Improve performance of some path expressions

- src/augeas.c
- src/internal.h
- tests/test-api.c
In a tree like /files/1/2, when we execute 'rm /files//*', the path
expression matches /files/1 and /files/1/2. When tree_rm goes to delete
these two nodes, it first deletes (frees) /files/1 and all its
descendents. By the time we try to delete /files/1/2, the pointer we have
to that is no longer valid and we end up causing a double-free.
With this change, we make sure we only delete a node if none of its
ancestors is being deleted beforehand in the same operation - deleting a
node, and one of its ancestors afterwards is fine as the pointer to the
ancestor is still valid.
Fixes https://github.com/hercules-team/augeas/issues/319
Special shoutout to Geoff Williams for finding, diagnosing and filing a
great bug report about this.
> aug_rm: fix segfault when deleting a tree and one of its ancestors

- NEWS
- src/pathx.c
- tests/xpath.tests
When we were evaluating path expressions, we were not skipping hidden tree
nodes, i.e. tree nodes whose label is NULL. In most cases, that's not
visible to users, but when we match something like /foo/*[2] where /foo has
a bunch of hidden children, the result was not what the user might expect,
as we might actually return a hidden node to aug_match, which would
suppress that node and make it seem to the user as if nothing had matched.
With this patch, we try to skip over hidden nodes while evaluating the path
expression to avoid this issue.
> Skip hidden tree nodes in path expressions

- lenses/nginx.aug
- lenses/tests/test_nginx.aug
I'm trying to learn how to use augtool so I copy pasted the nginx.conf from https://github.com/github/linguist/blob/master/samples/Nginx/filenames/nginx.conf
```nginx
user       www www;
worker_processes  5;
error_log  logs/error.log;
pid        logs/nginx.pid;
worker_rlimit_nofile 8192;
events {
worker_connections  4096;
}
http {
include    conf/mime.types;
include    /etc/nginx/proxy.conf;
include    /etc/nginx/fastcgi.conf;
index    index.html index.htm index.php;
default_type application/octet-stream;
log_format   main '$remote_addr - $remote_user [$time_local]  $status '
'"$request" $body_bytes_sent "$http_referer" '
'"$http_user_agent" "$http_x_forwarded_for"';
access_log   logs/access.log  main;
sendfile     on;
tcp_nopush   on;
server_names_hash_bucket_size 128; # this seems to be …
```
> nginx lense can't parse example from linguist

- lenses/shellvars.aug
- lenses/tests/test_shellvars.aug
This is the stock /etc/default configuration for aufs.
```bash
AUFS_VERSION=3.13-20140303
AUFS_SUPER_MAGIC=1635083891
AUFS_SUPER_MAGIC_HEX=0x61756673
AUFS_ROOT_INO=2
AUFS_WH_PFX=.wh.
AUFS_WH_PFX2=.wh..wh.
AUFS_MAX_NAMELEN=242
AUFS_WKQ_NAME=aufsd
AUFS_WH_DIROPQ=.wh..wh..opq
AUFS_WH_BASE=.wh..wh.aufs
AUFS_WH_PLINKDIR=.wh..wh.plnk
AUFS_WH_ORPHDIR=.wh..wh.orph
SetDir() # var dir
{
cd "$2"
eval "$1=\"$(pwd -P)\""
cd "$OLDPWD"
}
Esc() # [-e]
{
sed -r -e '
s/\\/\\134/g
s/$/\\012/
' |
tr -d '\n' |
sed -r -e '
s/ /\\040/g
s/\t/\\011/g
s/\r/\\015/g
s/\\012$//
' |
{ test $# -eq 1 &&
test "$1" = "-e" &&
sed -r -e 's/\\/\\\\/g' ||
cat; }
echo
}
FindMntEnt() # mntpnt
{
proc_mounts=/proc/self/mounts
test ! -e $proc_mounts && proc_mounts=/proc/$$/mounts
test ! -e $proc_mounts && proc_mounts=/proc/mounts …
```
> shelllvars lens fails for default configuration of aufs

- lenses/interfaces.aug
- lenses/tests/test_interfaces.aug
Current rule contains unconditional parse of interfaces.d subdirectory. But it is not valid, because Debian parses it only when instruction 'source-directory interfaces.d' specified in the /etc/network/interfaces file. Moreover, parser does not understand 'source-directory' instruction which causes empty tree.
Current rule: 
let filter = (incl "/etc/network/interfaces") . (incl "/etc/network/interfaces.d/*") . Util.stdexcl
> Invalid rules to parse /etc/network/interfaces

- lenses/logrotate.aug
Adds support for the 'dateyesterday' directive for logrotate.
I didn't add any tests for this as it is a trivial addition, and there are no existing tests for the other flags. I have, however, tested this locally with no issues. I'm happy to submit a new pull request with tests if that is preferred.
> logrotate: support dateyesterday option (GH #367)

- lenses/ntp.aug
Seen on Ubuntu Xenial (16.04), and not in the man page, but found references at https://www.freebsd.org/cgi/man.cgi?query=ntp.conf&sektion=5.
> Recent ntp.conf allows for 'pool' instead of 'server' et al

- src/fa.c
Return value of a function 'add_state' is dereferenced at fa.c:2776 without checking.
Added check on return value.
> DEREF_OF_NULL

- lenses/php.aug
php.ini has moved with upgrade from PHP5 to PHP7 (included in Ubuntu 16.04).
There is an additional folder for the version. Example for Apache's php.ini:
/etc/php/7.0/apache2/php.ini
Previously it was
/etc/php5/apache2/php.ini
Added the corresponding include line.
> Reflect Ubuntu 16.04 location of php.ini

- NEWS
- src/augtool.c
- src/get.c
- src/transform.c
- src/try
- tests/Makefile.am
- tests/root/etc/default/im-config
- tests/test-span-rec-lens.sh
The problem described in bug #397 is caused by an error handling memory when spans are enabled. The fix for this problem is the last patch in hte series, the others were merely minor unrelated things I encountered when fixing this bug.
> Fix memory corruption when using spans with a recursive lens (bug #397)

- NEWS
- examples/fadot.c
- src/augeas.c
- src/augrun.c
- src/builtin.c
- src/fa.c
- src/get.c
- src/info.c
- src/internal.c
- src/internal.h
- src/lens.c
- src/lexer.l
- src/pathx.c
- src/put.c
- src/syntax.c
- src/transform.c
- tests/cutest.c
- tests/cutest.h
- tests/fatest.c
- tests/test-api.c
- tests/test-load.c
- tests/test-perf.c
- tests/test-run.c
- tests/test-save.c
- tests/test-xpath.c
This fixes are all based on running augeas through [coverity](https://scan.coverity.com/projects/hercules-team-augeas).
> Various fixes based on coverity errors

- NEWS
- lenses/cron.aug
- src/parser.y
- src/syntax.c
- tests/modules/fail_invalid_regexp.aug
We used to not properly check the syntax of regular expressions that are
constructed. For example, in the construct
let rx = /a/ | /b)/
we would not check whether /b)/ is syntactically correct, which would later
lead to Augeas crashing. The reason for this was that literals had types
assigned to them before we actually checked them, i.e., the assumption was
that values didn't need any checking beyond setting their type, which is
not true for regular expressions.
> Properly check composite regular expressions for syntax errors

- NEWS
- lenses/cron_user.aug
- lenses/tests/test_cron_user.aug
- tests/Makefile.am
- tests/root/etc/crontab
- tests/root/var/spool/cron/root
The user crontab files in /var/spool/cron have a slightly different format
from /etc/crontab in that they do not have a 'user' field as that's implied
by the filename. Unfortunately, it is not possible to use Cron.lns, since
defining Cron.entry as
let entry       = [ label "entry" . indent
. prefix?
. ( time | schedule )
. (sep_spc . user)?
. sep_spc . store Rx.space_in . eol ]
(i.e., with a ( .. )? around the user name) leads to typecheck errors.
This lens is a minor variation on Cron.lns and just removes the bits about
the user field.
> Cron_User: new lens for user crontab files

- src/augeas.c
- src/transform.c
- src/transform.h
- tests/test-load.c
- tests/test-save.c
We used to blindly flag an error when there were multiple transforms that
handled the same file. That is now ok as long as these transforms all use
the exact same lens.
> Refine handling of multiple transforms handling the same file

- NEWS
- lenses/tests/test_xml.aug
- lenses/xml.aug
See http://www.w3.org/TR/2006/REC-xml11-20060816/#sec-external-ent for the
required syntax.
Based on initial patch by Adam Bottchen.
Fixes https://github.com/hercules-team/augeas/issues/142
> Xml: process external entities in DOCTYPE declaration

- lenses/yum.aug
My tests of the Yum lenses on DNF had no errors.  Added DNF configs to the import list.
> Yum lenses work on DNF, add them to import list

- lenses/krb5.aug
- lenses/tests/test_krb5.aug
Currently, the default kerberos configuration that ships with
Ubuntu has a realm that starts with a number (1TS.ORG). This
causes the parser to fail and prevents krb5.conf from being
available via augtool.
This patch allows numbers 0-9 as the first character of a
realm.
```
[realms]
~~<snip>~~
1TS.ORG = {
kdc = kerberos.1ts.org
admin_server = kerberos.1ts.org
}
```
> [krb5.aug] Support realms that start with numbers

- lenses/postfix_virtual.aug
- lenses/tests/test_postfix_virtual.aug
As per #439, understores are legal in an e-mail address.
> Allow underscores in postfix_virtual

- NEWS
- src/lens.c
- src/syntax.c
The pattern buffers for compiled regular expressions take up a large amount
of space. Previously, we had placed calls to lens_release strategically so
that that memory gets released when we are done with a lens for a while
(for example, after loading all files described by a transform)
That overlooked that the interpreter compiles regular expressions when it
loads lenses. We now also release lens storage after loading an entire
module. That requires that regular expressions are compiled again when we
start actually loading files, but the additional regex compilation does not
seem to affect the overall runtime. It does dramatically reduce maximum
memory needed by an 'augtool -L quit'. On my machine, it drops from about
90MB to about 20MB.
> Reduce the total amount of memory used by Augeas

- lenses/radicale.aug
- lenses/tests/test_radicale.aug
- tests/Makefile.am
This lens can parse /etc/radicale/config. It's a standard INI file, so the lens is basically the same as Puppet lens, except for the included path.
> Add lens for radicale config file

- lenses/rsyslog.aug
- lenses/tests/test_rsyslog.aug
Turns out module loads can have more than one option.  This fixes handling of that, and adds some related tests to be really sure.
> Fix for rsyslog rainerscript module loading, with options

- doc/naturaldocs/conf/lenses/Menu.txt
- lenses/nslcd.aug
- lenses/tests/test_nslcd.aug
- tests/Makefile.am
- tests/root/etc/nslcd.conf
Here's support for the /etc/nslcd.conf, the configuration file for nss-pam-ldapd (https://arthurdejong.org/nss-pam-ldapd/).
In the PR I've tried to include tests, an example file and some documentation that might help others use the lenses, but please let me know if something is missing.
> Add new nslcd.conf lenses to parse nss-pam-ldapd configuration file

- lenses/nginx.aug
Some of the configuration for nginx at least for Debian & Ubuntu can be found at `/etc/nginx/sites-available/`. These files are specific to each server nginx is going to proxy.
> Parse available sites for nginx

- NEWS
- src/lens.c
- src/lens.h
- src/put.c
- src/regexp.c
- src/regexp.h
These changes improve the error messages when transforming the tree back to a string by giving more context about where the error happened and what the tree was supposed to look like.
One example:
```
module T =
let nd (k:string) = [ key k ]
let lns = ((nd "a") | (nd "b"))*
let s = "ab"
test lns get s = { "a" } { "b" }
test lns put s after clear "/xkey[1]/typex" = ?
```
This used to produce the error
```
/tmp/t.aug:8.2-.49:exception thrown in test
/tmp/t.aug:8.7-.45:exception: Malformed child node 'xkey'
Lens: /tmp/t.aug:4.12-.34:
Error encountered at path
Syntax error in lens definition
Failed to load /tmp/t.aug
```
but now says
```
/tmp/t.aug:8.2-.49:exception thrown in test
/tmp/t.aug:8.7-.45:exception: Unexpected node '/xkey': can not match tree
{ "xkey" }
with pattern
(    { /a/ }
| …
```
> Improve put error messages

- lenses/rsyslog.aug
this is in response to the question I raised here: https://github.com/hercules-team/augeas/issues/465 -- just updating the rsyslog.aug lens so that it covers additional configuration files in the rsyslog.d directory.
Sorry it took so long to get back to it.
> update rsyslog lens to includ files in rsyslog.d dir

- lenses/sudoers.aug
The option is now enabled by default in the default sudoers of
RHEL 7.4 (and probably soon CentOS 7).
Closes #482
> Fix sudoers lens: recognize "match_group_by_gid"

- lenses/dovecot.aug
- lenses/postfix_access.aug
- lenses/postfix_main.aug
- lenses/postfix_master.aug
- lenses/postfix_passwordmap.aug
- lenses/postfix_sasl_smtpd.aug
- lenses/postfix_transport.aug
- lenses/postfix_virtual.aug
- lenses/shellvars.aug
Adds FreeBSD support for the Postfix lenses.
I noticed that other lenses don't change the comments (eg. `About: Configuration files`) to reflect the additional paths, so I didn't either. Glad to modify if needed.
> Add FreeBSD paths

- NEWS
- configure.ac
- examples/Makefile.am
- examples/dump.c
- src/augeas.c
- src/augeas.h
- src/augeas_sym.version
- src/internal.h
- src/pathx.c
- tests/test-api.c
This PR introduces new functions `aug_ns_*` which make it possible to iterate quickly over a large number of nodes and retrieve information for them. See `examples/dump.c` for how to use them and a small program that can be used to assess the performance improvement of these functions.
This is still work in progress, as it needs tests and some more thinking about error handling from `aug_ns_*`.
> WIP: speed up iterating and getting information about lots of nodes

- lenses/cgconfig.aug
- lenses/tests/test_cgconfig.aug
These keys are used to control the permissions for files and directories.
> Cgconfig: allow fperm & dperm in admin & task

- lenses/grub.aug
- lenses/tests/test_grub.aug
Grub 1 effectively ignores commands in the configuration which work only in the command line.  The generated configuration by anaconda included also a commented `boot=device` entry at the beginning: uncommenting that does not make the configuration invalid, but makes the Grub lens not able to parse it.
Since there is no harm in representing a configuration key that will be effectively ignored, accept top-level `boot` entries as well.
> Grub: handle top-level "boot" directive

- src/transform.c
- tests/Makefile.am
- tests/test-nonwritable.sh
When the file we are trying to save to is not writable, we left the
temporary file we wriote to behind. Now, we make sure we remove it.
Fixes https://github.com/hercules-team/augeas/issues/479
> When saving to nonwritable file fails, make sure we remove the tempfile

- NEWS
- lenses/tests/test_httpd.aug
- lenses/tests/test_json.aug
- src/lexer.l
- tests/modules/pass_lexer.aug
We used to look at a string literal like "\\" as not ending, and instead
mistook \" as escaping the ending quotes. This (longstanding, embarrassing)
bug would lead to weird syntax errors in lenses when encountered.
Fixes https://github.com/hercules-team/augeas/issues/495
> * src/lexer.l: properly handle backslash escaping in strings and regex

- src/augparse.c
Add aug_close() before exit to fix memory leak when printing
version information of augparse.
> Fix memory leak when checking version of augparse

- NEWS
- lenses/rsyslog.aug
- lenses/syslog.aug
- lenses/tests/test_rsyslog.aug
- lenses/tests/test_syslog.aug
These changes allow augeas to parse the default `/etc/rsyslog.conf` on Fedora 26
> Improvements of syslog and rsyslog

- NEWS
- lenses/exports.aug
- lenses/tests/test_exports.aug
We used to insist that paths start with a /, but things like
"/path/in/quotes" is legal, too. The lens now accepts pretty much anything
for the path now.
> Exports: allow paths in quotes

- NEWS
- src/put.c
- tests/modules/pass_create_del.aug
We already unescape the default for a del when we read the lens file. Doing
it during put will cause two rounds of unescaping to happen, which is
wrong.
Fixes: https://github.com/hercules-team/augeas/issues/507
> * src/put.c (create_del): do not unescape the string before writing it out

- NEWS
- lenses/properties.aug
- lenses/sshd.aug
- lenses/tests/test_properties.aug
- lenses/tests/test_sshd.aug
Fixes: https://github.com/hercules-team/augeas/issues/477
> Sshd: recognize quoted group names with spaces in them

- NEWS
- lenses/properties.aug
- lenses/tests/test_properties.aug
We now allow /\r?\n/ in line endings. The regular expressions preceding eol
and hard_eol are a little tighter than they really need to be to avoid
ambiguous concatenations as they generally result from removing \r from
allowable values. If that turns out to be a problem, we need to refine them
further.
Fixes https://github.com/hercules-team/augeas/issues/468
> Properties: accept DOS line endings

- lenses/getcap.aug
- lenses/rtadvd.aug
- lenses/termcap.aug
- lenses/tests/test_getcap.aug
- lenses/tests/test_rtadvd.aug
- lenses/tests/test_termcap.aug
- tests/Makefile.am
This is my stab at fixing #271 which seems to parse everything I've thrown at it including a ~900 KB termcap file. I can also add new records to files. However unless I disable type checking I get:
```
Syntax error in lens definition
./getcap.aug:34.2-.62:Failed to compile record
./getcap.aug:34.43-.54:exception: ambiguous iteration
Iterated regexp: /(([^:\n]|\\\\:)+|[^:\n]*(\\"[^\n]+\\"[^:\n]*)+)(:|:[ \t]*\\\\\n[ \t]*:)/
'\\:\\:\\::' can be split into
'\\:|=|\\:\\::'
and
'\\:\\:\\::|=|'
Iterated lens: ./getcap.aug:33.19-.61:
```
Any advice on cleaning that up would be appreciated.
I've tried writing some basic tests however I'm getting stuck where there should be a literal `\` in the output. If I try `\`-escaping it then I get something like the following:
```
Syntax error in lens …
```
> Add lens for reading termcap-style databases

- NEWS
- lenses/properties.aug
- lenses/resolv.aug
- lenses/tests/test_properties.aug
- lenses/tests/test_resolv.aug
- tests/root/etc/resolv.conf
@DaffyDuke could you just quickly check that the updated `resolv.aug` fixes Issue #161 for your case ? Since this is all about space and line endings, I don't want to solely rely on what I cut & paste out of github ;)
> Fix issue #161

- src/syntax.c
- src/transform.c
- tests/test-api.c
If a module name contains a '/', it can happen that we find the
module (like 'dist/Fstab.lns'), load it and then later can't find it under
the invalid module name containing the slash, leading to an endless loop of
loding the same module over and over again.
We avoid this by making sure there is no '/' in the module name before
looking for the module file. Other forms of invalid module names should not
cause similar problems as we will simply fail to find the corresponding
file.
Fixes https://github.com/hercules-team/augeas/issues/522
> Make sure we don't load a module but then later can't find it

- .gitignore
- NEWS
- man/Makefile.am
- man/augmatch.pod
- src/Makefile.am
- src/augeas.c
- src/augeas.h
- src/augeas_sym.version
- src/augmatch.c
- src/builtin.c
- src/info.c
- src/info.h
- src/internal.c
- src/internal.h
- src/lens.c
- src/pathx.c
There's a self-contained [static build](http://download.augeas.net/tmp/augmatch.tar.gz) with `augmatch`, lenses, and a sample root that will work on x86_64 Linux machines. After downloading and untarring, simply run `<dir>/augmatch`.
A container containing `augmatch` is also available on Docker Hub via `docker pull lutter/augmatch`. Running the container will put you into a shell with `augmatch` already set up.
Augeas so far has been very focused on making changes to configuration files, and making them safely. A side effect of how Augeas does what it does is that it provides a lot of structure for the files it parses. While it has always been possible to use that structure to query files via `augtool`, `augtool` is not really specialized for that use and makes it awkward for simple …
> New command line tool 'augmatch' for grepping through files

- lenses/httpd.aug
Fedora/RHEL uses this directory for modules config.
> httpd: include  /etc/httpd/conf.modules.d

- lenses/systemd.aug
logind.conf is also a ini file style config provided by systemd
> Add logind.conf to systemd lense

- NEWS
- lenses/systemd.aug
We used to get confused when writing back systemd changes and tried to
write a whole *.d or *.wants directory as one file, which would fail. By
explicitly not matching them, we make sure that we write to the files in
those directories, not the directories themselves.
Fixes https://github.com/hercules-team/augeas/issues/548
> Systemd: explicitly exclude *.d and *.wants directories

- src/augmatch.c
Fix memory leaks like following
```
==18340==
==18340== HEAP SUMMARY:
==18340==     in use at exit: 1,723 bytes in 258 blocks
==18340==   total heap usage: 2,005,764 allocs, 2,005,506 frees, 185,784,857 bytes allocated
==18340==
==18340== LEAK SUMMARY:
==18340==    definitely lost: 1,723 bytes in 258 blocks
==18340==    indirectly lost: 0 bytes in 0 blocks
==18340==      possibly lost: 0 bytes in 0 blocks
==18340==    still reachable: 0 bytes in 0 blocks
==18340==         suppressed: 0 bytes in 0 blocks
==18340== Rerun with --leak-check=full to see details of leaked memory
==18340==
==18340== For counts of detected and suppressed errors, rerun with: -v
==18340== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
> Fix several memory leaks in augmatch

- NEWS
- lenses/json.aug
- lenses/tests/test_json.aug
According to https://www.json.org/, a string like "\/" is legal in Json.
Fixes https://github.com/hercules-team/augeas/issues/557
> Json: allow escaped slashes in strings

- lenses/nginx.aug
On Debian/Ubuntu the active sites are configured in /etc/nginx/sites-enabled, either as files or as symlinks to files in /etc/nginx/sites-available/, so parse that path too.
> Parse nginx sites-enabled

- NEWS
- lenses/grub.aug
- lenses/tests/test_grub.aug
Refusing to parse an entire file because of invalid entries is too
harsh. Try to make the behavior a little friendlier by just mapping invalid
entries to '#error' nodes but still parsing the rest of the file.
> Grub: tolerate some invalid entries

- src/augtool.c
When stripping the context from the result, `readline_path_generator` used to realloc the string to a shorter size, copying only the content after the prefix.  This resulted in reading with `strcpy` from the previous memory, which is freed already.  Avoid the issue, and simplify the code by using `strdup`, freeing the old string.
This issue could be reproduced in `augtool`, trying to autocomplete files without the `/files` prefix, e.g.:
``
augtool> ls <TAB><TAB>
``
> augtool: fix access to invalid memory

- src/fa.c
Return earlier if `fopen` fails, otherwise `fa_dot` will dereference a null pointer.
> fa: check result of fopen

- NEWS
- lenses/httpd.aug
- lenses/tests/test_httpd.aug
We used to only deal with completely empty comments after a tag opening a
section, for example '<If cond>#\n', but not with a comment that consisted
only of whitespace like '<If cond># \n'. We now accept both cases,
resulting in the same tree.
Fixes https://github.com/hercules-team/augeas/issues/577
> Httpd: accept whitespace comment after tag opening a section

- NEWS
- src/pathx.c
In path expressions, we generally need to evaluate functions against every
node that we consider for the result set. For example, in the path
expression /files/etc/hosts/*[ipaddr =~ regexp('127\\.')], the regexp
function was evaluated against every entry in /etc/hosts. Evaluating that
function requires the construction and compilation of a new regexp. Because
of how memory is managed during evaluation of path expressions, the memory
used by all these copies of the same regexp is only freed after we are done
evaluating the path expression. This causes unacceptable memory usage in
large files (see https://github.com/hercules-team/augeas/issues/569)
To avoid these issues, we now distinguish between pure and impure functions
in the path expression interpreter. When we encounter a pure …
> Replace pure function invocations in path expressions with their result

- NEWS
- lenses/multipath.aug
- lenses/tests/test_multipath.aug
Multipath is happy with values enclosed in quotes, like 'path_checker
"tur"' in addition to the unquoted values. This change accepts such values
and strips the enclosing quotes.
Fixes https://github.com/hercules-team/augeas/issues/583
> Multipath: accept values enclosed in quotes

- src/lexer.l
flex by default generates the `input`, and `yyunput` functions; OTOH, augeas does not use them, so add the right options to suppress their generation.
> lexer: disable 'input' and 'yyunput' functions

- lenses/sudoers.aug
The option is now enabled by default in the default sudoers of
RHEL 7.6 (and probably soon CentOS 7).
> Fix sudoers lens: "always_query_group_plugin"

- NEWS
- lenses/semanage.aug
- lenses/simplevars.aug
- lenses/tests/test_semanage.aug
- tests/Makefile.am
Introduce a new lens to parse `/etc/selinux/semanage.conf` instead of using `Simplevars`: the latter cannot handle the more complex syntax of groups introduced in newer versions of libsemanage.
> New lens: Semanage

- NEWS
- lenses/pam.aug
- lenses/tests/test_pam.aug
Make it possible to use '\<LF>' as a whitespace character between tokens
Fixes https://github.com/hercules-team/augeas/issues/590
> Pam: accept continuation lines

- lenses/sshd.aug
Options in sshd_config cand be speciffied using space, tab or equal sign.
They all have the same effect.
> Allow parsing of options with equal sign

- lenses/rsyslog.aug
- lenses/tests/test_rsyslog.aug
In rsyslog.conf, #!, #+ and #- don't have a special meaning as they have in syslog, and therefore the usual Util.comment can and should be used.
> Rsyslog: bsd-like #!/+/- are just comments without special meaning

- lenses/tests/test_xorg.aug
- lenses/xorg.aug
In xorg.conf, values for options can be empty strings. This is seldom used, but there are use cases. In our case, we use an empty fbdev to keep autoprobing drivers, but disabling the fbdev driver. Another use case are Xkb layout options.
> Xorg: Accept empty values for options

- lenses/hostname.aug
```
$ augtool --version
augtool 1.8.0 <http://augeas.net/>
Copyright (C) 2007-2016 David Lutterkort
License LGPLv2+: GNU LGPL version 2.1 or later
<http://www.gnu.org/licenses/lgpl-2.1.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by David Lutterkort
```
---
Within augtool, the current `hostname` lens does not allow you to create a hostname entry under the following circumstances:
* /etc/hostname file is empty
* /etc/hostname file does not exist
There is no augtool command(s) that will allow you to add a hostname entry to an existing, but empty, file.  Example:
```
$ sudo rm /etc/hostname
$ sudo touch /etc/hostname
$ sudo augtool
augtool> set /files/etc/hostname/hostname myhostname
augtool> save …
```
> Allow Creation of Hostname When File is Missing

- lenses/logrotate.aug
- lenses/tests/test_logrotate.aug
Logrotate is able use quote filenames. This by itself is fixed there. Some
distributions files are using that. Logrotate would also be able to use files
with spaces (when quoted), fixing is too complicated for a quick fix and this
should be also uncommon in real life.
> Fixes missing recognition of double quoted filenames.

- lenses/shellvars.aug
Found tcsh profile scripts also with the `.tcsh` extension, so exclude them too.
Followup of commit b78bbb61282208288f0182ec1a9b3045c1f61e2a.
> Shellvars: exclude more tcsh profile scripts

- lenses/simplevars.aug
The OCS Inventory config file is a SimpleVars style config.
> Add ocsinventory-agent.cfg to SimpleVars

- .travis.yml
This was already used to build, and apparently it is not automatically available anymore.
>  * .travis.yml: install libtool-bin

- lenses/mke2fs.aug
- lenses/tests/test_mke2fs.aug
- parse more common entries between `[defaults]` and the tags in `[fs_types]`
- fix the type of few entries
- handle the `[options]` stanza
> Few improvements to the Mke2fs lens

- lenses/opendkim.aug
- lenses/tests/test_opendkim.aug
Modification done to match possible format of `/etc/opendkim.conf` file:
- Allow string values to start with numbers [0-9] like in `AutoRestartRate    10/1h`
- Allow string values to contain '/' like in `TrustAnchorFile    /usr/share/dns/root.key`
- Allow boolean values to start with uppercase letter: `False`, `True`, `Yes`, `No`
- Add support of parameter `LogWhy` with boolean value.
> Fix #643 - Update of opendkim lens to match current opendkim.conf file format

- lenses/grub.aug
- lenses/tests/test_grub.aug
This way it is possible to parse files that pass options with '+' in the name to the kernel.
> Grub: support '+' in kernel command line option names

- lenses/limits.aug
- lenses/tests/test_limits.aug
As the manpage for limits.conf describes, the domain field may contain colons ":" as part of either UID or GID ranges:
> * an uid range specified as <min_uid>:<max_uid>. If min_uid is omitted, the match is exact for the max_uid. If max_uid is omitted, all uids greater than or equal min_uid match.
> * a gid range specified as @<min_gid>:<max_gid>. If min_gid is omitted, the match is exact for the max_gid. If max_gid is omitted, all gids greater than or equal min_gid match. For the exact match all groups including the user's supplementary groups are examined. For the range matches only the user's primary group is examined.
--- quote `man limits.conf` on a Scientific Linus 7.5 machine with pam-1.1.8-22 installed
With this pull request, the colon is added to the domain pattern of Limits.lns …
> Support colons in the domain pattern of the limits lens

- lenses/fail2ban.aug
- lenses/tests/test_fail2ban.aug
- tests/Makefile.am
Add a lens to handle fail2ban configuration files.
These are Ini files.
Configuration is stored in /etc/fail2ban.
Ex on debian 9:
```
augtool print /files/etc/fail2ban/jail.d
/files/etc/fail2ban/jail.d
/files/etc/fail2ban/jail.d/defaults-debian.conf
/files/etc/fail2ban/jail.d/defaults-debian.conf/sshd
/files/etc/fail2ban/jail.d/defaults-debian.conf/sshd/enabled = "true"
```
> Add lens fail2ban

- lenses/logrotate.aug
Hourly is a valid logrotate schedule value.
> Add hourly schedule to logrotate lens.

- src/put.c
Recent changes (commit 4702d306fe01391af82dc1c7e2e1d50f571fda86) in this helper function cause the code after the `error` label to be used earlier than when `regs` is initialized; since the code in `error` frees a couple of the fields of the `regs` variable, then initialize `regs` earlier to avoid potential freeing uninitialized memory.
Found by Coverity.
> * src/put.c (split_concat): initialize regs earlier

- lenses/cmdline.aug
- lenses/tests/test_cmdline.aug
- tests/Makefile.am
Add lens to add linux cmdline files.
It is mostly to modify `/etc/kernel/cmdline` used by systemds kernel-install(8) command.
While `/proc/cmdline` can't be written, the lens allows structured introspection.
> Add Cmdline lens

- lenses/krb5.aug
- lenses/tests/test_krb5.aug
Improve the way `[dbmodules]` is parsed, and allow `include`/`includedir` everywhere.
> Krb5: improve [dbmodules] and includes

- lenses/systemd.aug
- lenses/tests/test_systemd.aug
Allow spaces inside of values quoted with single or double quotes.
This amends commit f64d8bc7a7670f3af2549fdcefb64c2b5f22cd0d that added support for quoted values.
TBH I'm not totally sure about it -- @raphink @domcleal can you please take a look whether it makes sense?
> Systemd: fix parsing of envvars with spaces

- lenses/mke2fs.aug
Seen it used by `mke2fs(8)`, so it must be handled as well.
> Mke2fs: add old_bitmaps option in [options]

- lenses/rx.aug
- lenses/tests/test_rx.aug
For some of the lenses I'm working on a URL is a possible parameter.  Having a default URL regex would simplify this for myself and others.
Since the RFC provides an approved regex, we may as well use that.
> lense: add RFC3986 URL regex

- NEWS
- src/lens.c
- tests/modules/fail_key_slash.aug
- tests/modules/fail_label_slash.aug
The '/' is only important in translating a string containing a path expression to the internal data structure we use to match it against a tree. It has no special meaning in the lens language
See https://github.com/hercules-team/augeas/issues/668 for more detail
> * src/lens.c: Do not require that keys and labels not match '/'

- augeas.pc.in
At the moment it is empty, so probably it does not exist. Remove it to avoid adding spurious content to the pkg-config file in case that variable will get a value in the future.
> lib: remove extra @LIBS@ from pkg-config file

- src/augeas.c
- src/pathx.c
- tests/Makefile.am
- tests/test-function-modified.sh
This Pull Request adds a new boolean function `modified()` to path-expressions.
The function `modified()` reads the status if the `dirty` flag of the context node,
and returns this as a boolean value.
The allows the current tree to be interrogated, showing which nodes have been modified 
since they where loaded.
eg:
```
augtool> set /files/etc/hosts/00/ipaddr 1.2.3.4
augtool> match /files//*[modified()]
/files/etc/hosts = (none)
/files/etc/hosts/00 = (none)
/files/etc/hosts/00/ipaddr = 1.2.3.4
augtool> 
```
This Pull Request alters the existing logic around the `dirty` flag in the tree, so that:
* only the actual nodes modified are marked 'dirty`, and _not_ the parent nodes of the modified node(s).
* the file-node of the modified node(s) is still marked `dirty`, as before
* all existing …
> Add function modified() to select nodes which are marked as dirty

- src/augeas.c
- src/augeas.h
- src/augeas_sym.version
- src/augrun.c
- src/augtool.c
- tests/test-api.c
This Pull Requests adds a new command `preview` to augtool, and a new function `aug_preview()` to the API.
The `preview` command accepts a path-name as an argument.
For the file corresponding to the path-name, the contents of the file are written to stdout, with the current
nodes and values from the `/files` tree applied.
This corresponds to the contents of the file that would be written by a subsequent `save` operation.
The path-expression must evaluate to a single node only, and the source-file is determined from this node.
The API call `aug_preview()` places the resulting file-contents into `char *OUT`, allocating the required memory.
int aug_preview(augeas *aug, const char *path, char **out);
> Add CLI command 'preview' and API 'aug_preview' to preview file contents

- lenses/sudoers.aug
- lenses/tests/test_sudoers.aug
Make sure to not confuse them with NIS groups.
These new directives were added in sudo 1.9.1.
> Sudoers: support new @include/@includedir directives

- lenses/tests/test_tmpfiles.aug
- lenses/tmpfiles.aug
- handle more type letters, according to what systemd-tmpfiles supports
- handle `-` characters for non-fatal rules
> Tmpfiles: few improvements to the types specification

- lenses/chrony.aug
- lenses/tests/test_chrony.aug
Add new directives and options supported in chrony since 3.3 up to 4.0.
The ntsport option is unsupported as it conflicts with the nts flag. I wasn't able to figure out how to resolve the conflict. The regex engine doesn't seem to support lookahead.
This should fix issue #697.
> Chrony: add new options

- lenses/sudoers.aug
- lenses/tests/test_sudoers.aug
Before this commit, `/etc/sudoers` files containing AD users or groups could not be parsed with the sudoers lens because it was containing `\\` in said users/groups name. Running `visudo -c` shows that a sudoers file containing these is valid so this case was added in the affected regex.
> Allow AD groups in '/etc/sudoers'

- lenses/mke2fs.aug
- lenses/tests/test_mke2fs.aug
`mke2fs.conf(5)` says that both tag names and values can be quoted using double quotes, in case they contain spaces. Sadly, the current Mke2fs lens does not support that.
In order to support this, introduce an helper `fspath` value to replace `Rx.fspath`, as the latter allows `"` as possible character (which we do not want in quoted strings).
Then change the helper `list_sto` and `entry_sto` functions to allow optionally double quoted values, with no changes in how the tree looks like.
Moreover, try to support also empty values, although only for lists at the moment.
> Mke2fs: support quoted values

- lenses/networkmanager.aug
- lenses/tests/test_networkmanager.aug
The lense will not encapsulate value of a newly created entry by quotes.
Values containing # are accepted (allowed character e.g. for WPA-PSK)
* For WPA-PSK each character in the pass-phrase must have an encoding in the range of 32 to 126 (decimal), inclusive. (IEEE Std. 802.11i-2004, Annex H.4.1)
E.g. # and space character are included in this range.
* adresses https://github.com/hercules-team/augeas/issues/719
> Modified NetworkManager lense

- lenses/sudoers.aug
- lenses/tests/test_sudoers.aug
[timestamp_timeout](https://help.ubuntu.com/community/RootSudoTimeout) in `/etc/sudoers` can have a negative value, but current augeas lens definition doesn't support this.
Modify lens regex to also match negative integers.
Issue is similar to https://libvir-list.redhat.narkive.com/gFPonY7Z/libvirt-patch-adapt-augeas-profile-to-handle-negative-int-values
> Support negative integers in sudoers lens

- src/pathx.c
- tests/run.tests
- tests/xpath.tests
This Pull Request adds a new binary operator to path-filter expressions.
The new operator is currently called `else`.
The existing binary operators `and` and `or` effectively act on 'sets' of nodes.
Given a filter-expression of the form:
*[nodeset_a or nodeset_b]
eg.
/files/etc/hosts/*[alias=~glob('local*') or ipaddr=~glob('192.168.*')]
nodeset_a and nodeset_b refer to a subset of `*` 
`*` represents all nodes at this level of the tree.
The `or` operator forms a union of nodeset_a and nodeset_b
Given a filter-expression:
*[nodeset_a and nodeset_b]
The `and` operator forms an intersection of nodeset_a and nodeset_b
The new binary operator `else` also deals with nodesets.
Given a filter-expression:
*[nodeset_a else nodeset_b]
The `else` operator acts as a 'selector' or 'order-of-priority' …
> Add "else" operator to augeas path-filter expressions (priority selector)

- AUTHORS
- lenses/authselectpam.aug
- lenses/tests/test_authselectpam.aug
- tests/Makefile.am
This solves #705 by adding `lenses/authselect_pam.aug`. The new lense is a copy of `lenses/pam.aug` but with authselect template syntax added. Additionally, the new lense only loads relevant files from authselect custom profiles. The new module name for this lense is `AuthselectPam`. The included test, `lenses/tests/test_authselect_pam`, passes and gives an idea of what the resulting tree looks like with the new syntax.
> Add authselect_pam.aug to lenses

- lenses/clamav.aug
ClamAV on Ubuntu uses a slightly different path.
> Add path for Ubuntu

- lenses/redis.aug
- lenses/tests/test_redis.aug
Before Redis 6.2 removing all the `SAVE` directives in the config file would disable snapshots. 
https://github.com/redis/redis/blob/6.0/redis.conf#L299-L305
In Redis 6.2 removing all the `SAVE` directives in the config file will result in having snapshots enabled.
https://github.com/redis/redis/blob/6.2/redis.conf#L369-L377
To disable snapshots in Redis 6.2 requires setting `SAVE ""` as a line in the config file. This change allows the Redis lens to use `SAVE ""` a valid directive in the Redis configuration. Without this change, snapshots cannot be disabled using this lens.
Using `SAVE ""` to disable snapshots has been valid syntax since Redis 2.8
https://github.com/redis/redis/blob/2.8/redis.conf#L141-L145
> Allow Redis lens to set `SAVE ""` as a valid option

- lenses/kdump.aug
- lenses/tests/test_kdump.aug
- tests/root/etc/kdump.conf
~~~
The "auto_reset_crashkernel" keyword was introduced in the following
kexec-tools patch set:
[PATCH v5 00/13] crashkernel=auto: support fadump and remove
crashkernel.default
https://lists.fedoraproject.org/archives/list/kexec@lists.fedoraproject.org/thread/V5WPTRAPJR65QXSTNW6W6E7ZBAUCQNUH/#V5WPTRAPJR65QXSTNW6W6E7ZBAUCQNUH
Related upstream commit:
https://src.fedoraproject.org/rpms/kexec-tools/c/73ced7f451a72
Recognize "auto_reset_crashkernel" in "kdump.aug". Update the test case.
Also copy "kdump.conf" from kexec-tools @ 73ced7f451a72 to
"tests/root/etc/kdump.conf".
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2042772
Signed-off-by: Laszlo Ersek <lersek@redhat.com>
~~~
> Kdump: parse "auto_reset_crashkernel"

- lenses/tests/test_toml.aug
- lenses/toml.aug
The toml lens fails to save simple toml files due to problems with multi
dimensional (>2) arrays.
Therefore disable arrays with more than 2 dimensions for now to enable
basic usage again.
This commit fixes issue #715 by applying the suggested workaround. If
anyone can come up with a better solution please feel free to do so.
Fixes: 5e1cd313 (TOML lens (#91), 2018-11-29)
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>
> fix(lens): toml: write support

- .github/workflows/release.yml
To see how this works, see the [Releases](https://github.com/hillu/augeas/releases) in my fork where a release attached to the `v42` tag should appear soon.
This should fix #741 for future releases of Augeas
> Add Github workflow to create releases with complete source tarballs

- augeas.spec.in
Otherwise rpmbulld fails with 'Installed (but unpackaged) file(s) found' error.
> augeas.spec to include augmatch into a list of files

- src/syntax.c
Coverity reports the error below.  (The actual error comes from the
compiler used, rather than Coverity).
This is because the va_start line uses a tab while the line following
uses 4 spaces.  When you view the file in a tool like "less", the tab
appears as 8 spaces, so it appears to be indented confusingly.  When
you open the file in Emacs, the local variables clause at the end
causes tabs to be set to 4 characters so there is no visible
difference.
Anyway the fix is a trivial whitespace change.
Error: COMPILER_WARNING (CWE-483): [#def32]
augeas-1.12.0/src/syntax.c: scope_hint: In function 'syntax_error'
augeas-1.12.0/src/syntax.c:134:5: warning[-Wmisleading-indentation]: this 'if' clause does not guard...
augeas-1.12.0/src/syntax.c:26: included_from: Included from here. …
> src/syntax.c: Fix whitespace which confuses static checkers

- src/transform.c
https://github.com/SELinuxProject/selinux/commit/7a124ca275
https://github.com/SELinuxProject/selinux/pull/212/files
> Replace deprecated 'security_context_t' with 'char *'

- lenses/semanage.aug
- lenses/tests/test_semanage.aug
- tests/root/etc/selinux/semanage.conf
- tests/xpath.tests
From /etc/selinux/semanage.conf from a RHEL 9.1 system, this line
caused problems:
ignoredirs=/root;/bin;/boot;/dev;/etc [...]
Parse this as a list of Rx.fspath.
Also this adds the RHEL 9 file as another test case and adjusts the
output of the existing test case.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2077120
Signed-off-by: Richard W.M. Jones <rjones@redhat.com>
> semanage: Fix parsing of ignoredirs

- lenses/sshd.aug
- lenses/tests/test_sshd.aug
Several configuration values used for setting crypto policy were being
incorrectly parsed as raw strings when they are in fact lists. Treat
them as such
Specifically:
- GSSAPIKexAlgorithms
- PubkeyAcceptedKeyTypes
- CASignatureAlgorithms
> Update sshd lens to split additional list keys

- augeas.spec.in
- configure.ac
- src/Makefile.am
- src/augmatch-completion.bash
- src/augprint-completion.bash
- src/augtool-completion.bash
This adds bash-completion files for the commands:
* augtool
* augmatch
* augprint
> Add bash-completion for augtool, augmatch, augprint

- lenses/resolv.aug
- lenses/tests/test_resolv.aug
Update existing lens for /etc/resolv.conf (resolv.aug) to include option `trust-ad`
Updated test `test_resolv.aug` to include `option trust-ad`
> Update lens Resolv: add option trust-ad

- lenses/tests/test_yum.aug
When writing a new lense using logic from this lense I uncovered unexpected behaviour with whitespace.
The tests added here expose this oddity.
> Add additional unit tests for yum lense

- src/augprint.c
Hi! Submitting this patch to fix the build error in Homebrew/homebrew-core#118025.
`<malloc.h>` is not present on all platforms (e.g. macOS). To use `malloc`, `<stdlib.h>` should be the place to look for `malloc`, and it has already been `#include`d.
Signed-off-by: Ruoyu Zhong <zhongruoyu@outlook.com>
> Remove `#include <malloc.h>`

- lenses/cmdline.aug
- lenses/tests/test_cmdline.aug
Reported-by: Yongkui Guo
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2159282
Signed-off-by: Richard W.M. Jones <rjones@redhat.com>
> lenses: Allow whitespace at the end of kernel commnd line

- HACKING.md
The top-level HACKING document is inexplicably silent on how bugs can be reproduced/triggered and how fixes/features can be verified. That's an unnecessary difficulty for anyone new trying to contribute to augeas.
Document "make check", and highlight the difference between "test-get.sh" and the individual lens tests under "lenses/tests/".
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2155147
Signed-off-by: Laszlo Ersek <lersek@redhat.com>
> HACKING.md: describe testing

- lenses/sshd.aug
- lenses/tests/test_sshd.aug
> Update sshd lens for additional list

- lenses/tests/test_tmpfiles.aug
- lenses/tmpfiles.aug
- recognize `=`, `~`, `^` for the type specification (fixes #795)
- allow `:` as prefix for file modes
> Tmpfiles: few improvements

- src/augeas.c
- tests/Makefile.am
- tests/test-createfile.sh
Pull Request #691 introduced a new function to path expressions `modified()`
This function exposed the value of the internal flag `dirty` on a node.
In order for `modifed()` to reflect _only_ the changed nodes, some of the logic around the `dirty` flag was modified.
This caused a bug which appeared after a `save`operation, where upon a subsequent `load` operation, where the nodes of a newly created file were inadvertently  removed.
This PR fixes the inadvertent cleanup on the subsequent load operation, if the file has been saved.
Unsaved nodes under `/files` are still cleaned up by the load operation
> Fix bug from PR#691 where the nodes of a newly created file are lost upon a subsequent load operation

- src/internal.c
As reported in https://pkg-status.freebsd.org/gohan05/data/maini386PR265425-default/2022-12-06_12h24m32s/logs/errors/augeas-1.12.0_3.log, augeas uses a GNU specific `strerror_r()` invocation, even when compiling on FreeBSD. This is because gnulib's `regex.h` defines `__USE_GNU` when `_GNU_SOURCE` is used.
It is better to also check for `__GLIBC__`, since the GNU specific variant of `strerror_r()` is really a glibc invention. This will also make the code compile without warnings on Alpine Linux, which uses musl libc.
> Only use GNU specific strerror_r() API when __GLIBC__ is defined.

- src/augmatch.c
- src/lens.h
Tested with:
```
./autogen.sh --enable-debug=no --enable-compile-warnings=maximum
make distcheck
```
and
```
./autogen.sh --enable-debug=yes --enable-compile-warnings=maximum
make distcheck
```
Fixes issue #817
> Fix some compiler warnings in lens.c, augmatch.c

- lenses/ntp.aug
- lenses/tests/test_ntp.aug
- fixed lens parser fails on 'tos/minclock' (/etc/ntpsec/ntp.conf on debian12 with that line "tos minclock 4 minsane 3" )
- filter : add /etc/ntpsec/ntp.conf
> Fix lens ntp.aug (tos/minclock) and support ntpsec conf file (Debian12)

- lenses/fstab.aug
- lenses/tests/test_fstab.aug
This PR adds a new lens that allows a comma after the last option:
```
/dev/mapper/foo-bar / xfs defaults, 0 0
```
Fixes: https://github.com/hercules-team/augeas/issues/832
Signed-off-by: cosmin@redhat.com
> lenses/fstab.aug: Allow comma after the last option

- lenses/multipath.aug
Fixes: https://issues.redhat.com/browse/RHEL-39080
> lenses/multipath.aug: Support all possible values for find_multipaths

- src/internal.h
Current code doesn't work on LLVM. This should fix it so it works on gcc and llvm.
> Make ATTRIBUTE_FALLTHROUGH work cross-compiler

- acinclude.m4
- src/augprint.c
- src/get.c
- tests/test-api.c
Fix miscellaneous GCC warnings.  In particular this causes the compile to fail when using `configure --enable-compile-warnings=error` and using a recent version of GCC.
> Fix gcc warnings

- lenses/systemd.aug
- lenses/tests/test_systemd.aug
This commit allows the "+"(fullprivileges) command flag along with "-" and "@" flags.
Fixes: #839
> lenses/systemd.aug: Allow "+"(fullprivileges) command flag

- lenses/tests/test_tmpfiles.aug
- lenses/tmpfiles.aug
In Fedora 42 & RHEL 10 we see:
$ cat /usr/lib/tmpfiles.d/systemd.conf
...
d$ /run/systemd/seats 0755 root root -
...
where the '$' means (from tmpfiles.d(5)):
If the dollar sign ("$") is used, the file becomes subject to
removal when systemd-tmpfiles is invoked with the --purge
switch. Lines without this character are unaffected by that switch.
Fixes: https://issues.redhat.com/browse/RHEL-76283
> lenses/tmpfiles.aug: Permit '$' character in /usr/lib/tmpfiles.d/*.conf
