src/augtool.c

This patch provides more familiar shell-like handling of Ctrl-C, where the current line is cancelled instead of exiting the shell entirely. It doesn't handle modes like incremental search optimally, though. Ideally, Ctrl-C would just exit incremental search as well (behaving exactly like Ctrl-G), but in practice, it just reprints the i-search prompt. Still, you can just Ctrl-G out of it, so it's not that big a deal. Maybe someone else knows how to fix this.

augtool: on interrupt, cancel current line instead of exiting

---

NEWS
lenses/nginx.aug
lenses/tests/test_nginx.aug
tests/root/etc/nginx/nginx.conf

This patch should fix Issue #179

Nginx: rework to support a much broader set of valid configurations

---

lenses/openvpn.aug
lenses/tests/test_openvpn.aug

I've added all possible options in OpenVPN 2.3 from the man page at https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage and tests for lots (all?) permutations of those options.

openvpn: added all options available in OpenVPN2.3 and all tests

---

lenses/chrony.aug
lenses/tests/test_chrony.aug

The first patch adds support for new directives and options introduced in recent chrony versions. The second patch adds support for forms of the allow/deny directives that use no address or the all option.

Improve chrony lens

---

lenses/inputrc.aug
lenses/tests/test_inputrc.aug

Inputrc fixes

---

lenses/chrony.aug
lenses/tests/test_chrony.aug

chrony-2.4 will have a new maxdrift directive and new options for the local directive.

Chrony: add new options

---

lenses/ntp.aug
lenses/tests/test_ntp.aug

Restrict now can also have -4, so ipv6 no longer have sense alone, so changed to "ip" key with value "4" or "6". Also tests are adapted to new behavior

fix restrict to allow also -4 and also fix save/store ability

---

NEWS
src/augtool.c
src/get.c
src/lens.h
src/put.c
src/transform.c
src/try
tests/Makefile.am
tests/root/etc/default/im-config
tests/test-span-rec-lens.sh

This fixes the problem reported in bug #398

Fix illegal memory access in skel_instane_of

---

lenses/krb5.aug
lenses/tests/test_krb5.aug

I don't know Augeas lenses that well, but looking at some others that have includes in them as examples, this might be a possible fix to Issue #430 that I submitted.

Possible fix to #430

---

lenses/chrony.aug
lenses/tests/test_chrony.aug

Add new directives and options from chrony-3.0 and chrony-3.1.

Chrony: add new directives and options

---

NEWS
src/augeas.c
src/augeas.h
src/augeas_sym.version
src/augrun.c
src/augtool.c
src/internal.h
src/transform.c

Fixes https://github.com/hercules-team/augeas/issues/384

Add a new aug_source API call and 'source' command in augtool

---

lenses/tests/test_xymon.aug
lenses/xymon.aug

A suitable test added to the test_xymon.aug for group-sorted.

Xymon.aug: Add group-sorted to definitions

---

NEWS
lenses/oz.aug
lenses/tests/test_oz.aug
tests/Makefile.am

Yet another ini style config file.

New lense for OZ

---

lenses/tests/test_yaml.aug
lenses/yaml.aug

This only adds support for a document which
consists of a sequence.

Support YAML sequence documents

---

src/augparse.c
src/jmt.c
src/pathx.c
src/syntax.c
src/transform.c
tests/Makefile.am

Fix a few memory leaks, mostly in error situations, or debugging.
Also fix the run of `make check` in the `valgrind` target.

Fix few minor memory leaks

---

NEWS
lenses/redis.aug
lenses/tests/test_redis.aug

Fixes https://github.com/hercules-team/augeas/issues/194

Redis: accept bind command

---

lenses/krb5.aug

Updated the krb5 lense to handle more pkinit_* config options.

Added more pkinit_* options.

---

lenses/dovecot.aug
lenses/tests/test_dovecot.aug

Permit ! in dovecot block titles

---

lenses/nsswitch.aug

The action "merge" is allowed in nsswitch:
https://www.gnu.org/software/libc/manual/html_node/Actions-in-the-NSS-configuration.html
This was added in glibc 2.24:
https://abi-laboratory.pro/?view=changelog&l=glibc&v=2.24

nsswitch: Add action merge

---

lenses/puppetfile.aug
lenses/tests/test_puppetfile.aug

This aims to fix https://github.com/camptocamp/puppetfile-updater/issues/13
There might still be quite a few edge cases that will not work, because it's horrible :wink:

Puppetfile: allow comments in entries

---

lenses/nginx.aug
lenses/tests/test_nginx.aug

@Salokyn does that solve it for you?

Support unix sockets as server address (fix #617)

---

lenses/rsyslog.aug
lenses/tests/test_rsyslog.aug

As per https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/s1-basic_configuration_of_rsyslog#s2-Actions

Rsyslog: support dynamic file paths

---

lenses/authinfo2.aug
lenses/tests/test_authinfo2.aug
tests/Makefile.am

Add lens Authinfo2

---

src/augrun.c
src/augtool.c

- improve the readline integration to handle quoted characters like spaces in paths
- recognize more quoted characters for paths

A couple of augtool completion fixes

---

README.md

real minor, thanks for a great project

README.md: fix minor typo

---

lenses/postfix_transport.aug
lenses/tests/test_postfix_transport.aug

Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>

Allow underscore in postfix_transport

---

src/fa.c

Fixed possible error.
Also: I'm trying to build my project (my reversible analog of flex) on top of libfa. I can tell more if you want

src/fa.c: fixed error in regexp grammar in comment

---

lenses/ssh.aug
lenses/tests/test_ssh.aug

Signed-off-by: Guillaume Ranquet <guillaume-externe.ranquet@edf.fr>
Proposal for a fix regarding https://github.com/hercules-team/augeas/issues/632

Ssh: add Match keyword support

---

lenses/resolv.aug

Update the resolv lens

---

lenses/crypttab.aug
lenses/tests/test_crypttab.aug

Crypttab: support UUID in device and / in opt

---

lenses/tests/test_tinc.aug
lenses/tinc.aug
tests/Makefile.am

This lens can handle configurations for Tinc VPN ( https://tinc-vpn.org/ )

add tinc lens

---

lenses/redis.aug

Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>

feat(lenses): add /etc/redis.conf to Redis.lns

---

lenses/redis.aug
lenses/tests/test_redis.aug

- feat(lenses): add /etc/redis.conf to Redis.lns
- feat(lens): Support replicaof stanza in Redis.lns

feat(lens): Support replicaof stanza in Redis.lns

---

lenses/systemd.aug
lenses/tests/test_systemd.aug

Fixes of `systemd` lens as described in the commit messages, tests included.

Systemd lens fixes

---

lenses/keepalived.aug
lenses/tests/test_keepalived.aug

https://www.keepalived.org/manpage.html

keepalived lense add notify_stop and notify_deleted parameters

---

docker/Dockerfile

Fixes #769
Fixes problem 1 (as described in #769) , problem 2 (as described) is fixed by #747

Add package bash to build stage in Dockerfile

---

lenses/pg_hba.aug
lenses/tests/test_pg_hba.aug

Fixes issue #775 
Similar to PR #701

Pg_Hba: unquoted auth-method may contain hyphens

---

lenses/cockpit.aug
lenses/tests/test_cockpit.aug
tests/Makefile.am

lense: cockpit.conf

---

NEWS
configure.ac

Updated `NEWS` and `configure.ac`

Version 1.14.0

---

lenses/chrony.aug
lenses/tests/test_chrony.aug

This PR adds support for "leapseclist" option.
Fixes: #840 
Signed-off-by: Cosmin Tupangiu <cosmin@redhat.com>

lenses/chrony.aug: Add support for leapseclist
